[tool.poetry]
name = "vampires-dpp"
version = "0.1.0"
description = "Tools for processing VAMPIRES data"
authors = ["Miles Lucas <mdlucas@hawaii.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.22.2"
astropy = "^5.0.1"
tqdm = "^4.62.3"
scikit-image = "^0.19"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^22"
