version = "0.1.0" # vampires_dpp version

name = "example" # simple name for analysis, used for automatic naming of some files
directory = "" # root directory, will use CWD by default
output_directory = "" # path to top-level output directory, if empty will use the current working directory

[coronagraph] # these options only matter if `coronagraphic = true`
mask_size = 90 # IWA of mask, mas

[coronagraph.satellite_spots]
radius = 15.9 # radius of satellite spots in lam/D
angle = -4 # angle offset of satellite spots in degrees, -4 is default

[calibration]
filenames = [""] # list of filenames, the path to a textfile with names, or a python glob expression
output_directory = "" # output directory, if empty will use same directory as files
force = false # if calibrated file already exists, should we force the calibration and overwrite?

[calibration.darks]
filenames = [""] # list of filenames, the path to a textfile with names, or a python glob expression
output_name = "master_dark" # master dark name
force = false # if file already exists, should we force the calibration and overwrite?

[calibration.flats]
filenames = [""] # list of filenames, the path to a textfile with names, or a python glob expression
output_name = "master_flat"
force = false # if file already exists, should we force the calibration and overwrite?

[frame_selection]
metric = "l2norm" # frame selection metric, one of 'max', 'l2norm', 'normvar'
q = 0.0 # frame selection quantile [0, 1). 0 is no frame seleciton, 1 removes all frames
output_directory = "" # output directory for measured metrics and intermediate frames
force = false # if files already exist, should we force the calculation and overwrite?
window_size = 30 # window size to measure offsets from

[registration]
method = "com" # offset measurement method, one of 'com', 'max', 'dft', 'moffat', 'airydisk', 'gaussian'
window_size = 30 # window size to measure offsets from
output_directory = "" # output directory for measured offsets and intermediate frames
force = false # if files already exist, should we force the calculation and overwrite?

[registration.dft] # options only for the 'dft' registration method
upsampling_factor = 10 # the sub-pixel precision of the upsampled DFT
reference_method = "com" # how to measure the offset of the reference frame

[coadd]
output_directory = "" # output directory for intermediate frames
force = false # if files already exist, should we force the calculation and overwrite?