name: CI
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
  paths-ignore:
    - "docs/**"
jobs:
  test:
    name: Python ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ["3.7", "3.8", "3.9"]
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch: ["x64"]
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
      - name: Run pytest
        run: pytest --cov vampires_dpp --cov-report xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          