name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install dependencies
        run: |
            pip install -U pip
            pip install .[docs]
      - name: Deploy with MkDocs
        run: |
            echo "mileslucas.com/vampires_dpp" > "${GITHUB_WORKSPACE}/docs/CNAME"
            config_file="${GITHUB_WORKSPACE}/mkdocs.yml"
            remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
            git remote rm origin
            git remote add origin "${remote_repo}"
            mkdocs gh-deploy --config-file "$config_file" --force
